### ISSUE TITLE
Kicks Operator when using LuckPerms

### ISSUE THREAD

**Issue by Merith-TK** [AlphaMode/CompactMachines-Fabric#1]
### I am not using performance mods.

- [X] Confirm

### Description

So the first checkbox is an lie,

but it effectively gives the same data as an "chunk ban" when an OP tries to join an server while LuckPerms is enabled 

![image](https://user-images.githubusercontent.com/10422110/180668645-94fd31be-967f-4ce1-8374-68d80fcf5e96.png)

WE blieve this is the mod responsible as it shows to overwrite MC Commands (preventing `/tp` while in an compact machine, which is an very big issue as an player can become permanently trapped in one if they loose thier Personal Shrinking Device)

### Mod Version

4.3.0.4

### Forge Version

Fabric 1.18.2, 0.14.8

### Screenshot (if available)

![image](https://user-images.githubusercontent.com/10422110/180668674-67de8167-e1e0-41bc-a438-95082c173a90.png)
![image](https://user-images.githubusercontent.com/10422110/180668676-d1c20a64-1d11-40f9-bfec-6e48e28e6e4b.png)

I can recreate this on the fly by `/op` myself, 

### How to reproduce

1. Luckperms
2. This mod
3. Join Server
4. Op yourself

**Comment by AlphaMode** [comment]
Anything error in the client/server log?

**Comment by Merith-TK** [comment]
yeah, serverside, client just freaks out like it gets chunk/book banned

Server Logs
```
[22:55:10] [Server thread/INFO]: [Mekrath: Made Mekrath a server operator]
[22:55:10] [Netty Epoll Server IO #2/ERROR]: Could not serialize dev.compactmods.machines.upgrade.command.RoomUpgradeArgument@6ef01c0d (class dev.compactmods.machines.upgrade.command.RoomUpgradeArgument) - will not be sent to client!
[22:55:10] [Netty Epoll Server IO #2/ERROR]: Could not serialize dev.compactmods.machines.upgrade.command.RoomUpgradeArgument@7e85ea9e (class dev.compactmods.machines.upgrade.command.RoomUpgradeArgument) - will not be sent to client!
[22:55:11] [Server thread/INFO]: Mekrath lost connection: Disconnected
[22:55:11] [Server thread/INFO]: Mekrath left the game
```

Client Logs
```
[15:55:09] [Netty Client IO #13/ERROR]: Could not deserialize minecraft:
[15:55:09] [Netty Client IO #13/ERROR]: Exception occurred in netty pipeline
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(48871) + length(1) exceeds writerIndex(48871): PooledUnsafeDirectByteBuf(ridx: 48871, widx: 48871, cap: 48871)
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:477) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(48871) + length(1) exceeds writerIndex(48871): PooledUnsafeDirectByteBuf(ridx: 48871, widx: 48871, cap: 48871)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-all-4.1.68.Final.jar:?]
	at net.minecraft.network.PacketByteBuf.readByte(PacketByteBuf:1013) ~[?:?]
	at net.minecraft.network.PacketByteBuf.readVarInt(PacketByteBuf:344) ~[?:?]
	at net.minecraft.network.PacketByteBuf.readIntArray(PacketByteBuf:237) ~[?:?]
	at net.minecraft.network.PacketByteBuf.readIntArray(PacketByteBuf:233) ~[?:?]
	at net.minecraft.network.packet.s2c.play.CommandTreeS2CPacket.readCommandNode(CommandTreeS2CPacket:103) ~[?:?]
	at net.minecraft.network.PacketByteBuf.readCollection(PacketByteBuf:123) ~[?:?]
	at net.minecraft.network.PacketByteBuf.readList(PacketByteBuf:136) ~[?:?]
	at net.minecraft.network.packet.s2c.play.CommandTreeS2CPacket.<init>(CommandTreeS2CPacket:47) ~[?:?]
	at net.minecraft.network.NetworkState$PacketHandler.createPacket(NetworkState:419) ~[?:?]
	at net.minecraft.network.NetworkState.getPacketHandler(NetworkState:471) ~[?:?]
	at net.minecraft.network.DecoderHandler.decode(DecoderHandler:32) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[netty-all-4.1.68.Final.jar:?]
	... 36 more
```

![image](https://user-images.githubusercontent.com/10422110/180669178-e5d804d7-e12a-455c-bdce-2fb07dd9d024.png)

**Comment by AlphaMode** [comment]
Thanks for reporting it should be fixed now I'll upload a new build to curseforge soon

**Comment by AlphaMode** [comment]
Alright the newest version should fix the issue 
[https://modrinth.com/mod/cpm-fabric/version/4.4.0.6](https://modrinth.com/mod/cpm-fabric/version/4.4.0.6)
[https://www.curseforge.com/minecraft/mc-mods/compact-machines-fabric/files/3898464](https://www.curseforge.com/minecraft/mc-mods/compact-machines-fabric/files/3898464)
